const expenseUserTypes = {
  REGISTER_EXPENSE_START: "REGISTER_EXPENSE_START",
  REGISTER_EXPENSE_SUCCESS: "REGISTER_EXPENSE_SUCCESS",
  REGISTER_EXPENSE_FAILURE: "REGISTER_EXPENSE_FAILURE",
  LOG_USER_OUT: "LOG_USER_OUT",
};

export default expenseUserTypes;
