const authUserTypes = {
    REGISTER_USER_START: "REGISTER_USER_START",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
    LOG_USER_OUT: "LOG_USER_OUT",
  };
  
  export default authUserTypes;
  